version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"

    # Обновлять только production-зависимости
    # и не создавать слишком много PR одновременно
    open-pull-requests-limit: 10

    # Группировать обновления зависимостей
    groups:
      python-dependencies:
        patterns:
          - "*"
